name: task_manager
description: "A simple task management app"
publish_to: 'none'
version: 0.1.0+19

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^9.0.0
  build_runner: ^2.4.9
  collection: ^1.18.0
  crypto: ^3.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^19.4.2
  flutter_settings_screen_ex: ^0.0.1+5
  flutter_timezone: ^4.1.1
  get_it: ^8.2.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.1
  rrule: ^0.2.17
  settings_ui: ^2.0.2
  sqflite: ^2.3.2
  test: ^1.25.7
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
